openvino with gpu install
AovoT/AT-Docs pull request #45
Opened 2024-04-11 11:57 UTC by faixiaohai

2024-04-16 09:27 UTC, yxSakana requested changes
cmake文件修改，测试代码应该有针对性且简洁明了

2024-04-16 09:27 UTC, yxSakana commented on src/openvino/OpenVINO.md
> +#include <inference_engine.hpp>
头文件的包含顺序按照Google开源项目风格指南上来

2024-04-16 09:27 UTC, yxSakana commented on src/openvino/OpenVINO.md
> +## 四.示例代码(基于InferenceEngin)
cmake文件按照我写的那个来，示例/测试代码应当有针对性并且简洁明了，把非GPU测试代码全部剔除

2024-04-16 10:26 UTC, faixiaohai commented on src/openvino/OpenVINO.md
> +#include <inference_engine.hpp>
现在改了

2024-04-17 01:51 UTC, yxSakana approved these changes

2024-04-17 01:53 UTC, merged